[package]
name = "fishsteam-sys"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
steamworks = { version = "0.7.0" }
nanoserde = "0.1"

[patch.crates-io]
steamworks = { git = "https://github.com/not-fl3/steamworks-rs", branch = "lobby_chat_update" }
